name: Deploy Hotel MENU (Docker, self-hosted)

on:
  push:
    branches: [ master ]

env:
  APP_NAME: hotel-menu       # Container name
  IMAGE_NAME: hotel-menu     # Local image name
  COMPOSE_FILE: docker-compose.yml

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30
    
    steps:
      # Checkout the latest code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # (Optional) Set up Buildx for faster builds and layer caching
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image with two tags: commit SHA and latest
      - name: Build Docker image
        run: |
          docker build \
            --pull \
            -t $IMAGE_NAME:${GITHUB_SHA} \
            -t $IMAGE_NAME:latest \
            .

      # Deploy using Docker Compose
      - name: Deploy with Docker Compose
        run: |
          # Stop and remove existing containers if running
          docker compose -f $COMPOSE_FILE down || true
          # Start with the newly built image
          docker compose -f $COMPOSE_FILE up -d --force-recreate
          # Remove unused images to save space
          docker image prune -f
